NDefines.NCountry.COUNTRIES_GETTING_SCORE = 0
NDefines.NMilitary.WARGOAL_MAX_BONUS = 50
NDefines.NDiplomacy.MIN_RELATIONS_TO_ALLY = -200

NDefines.NDiplomacy.CHANGE_RIVAL_YEARS = 0
NDefines.NCountry.PS_REPLACE_RIVAL = 0

NDefines.NCountry.NAT_FOCUS_YEARS = 15

NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_HUNDRED_DEVASTATION = -0.5
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_5_LOANS = 0

NDefines.NCountry.MAX_IDEA_GROUPS_FROM_SAME_CATEGORY = 0.4

NDefines.NMilitary.NAVAL_BASE_ENGAGEMENT_WIDTH = 600
NDefines.NMilitary.NAVAL_BASE_DISENGAGEMENT_CHANCE = 0
NDefines.NMilitary.NAVAL_CASUALTY_MIN_MORALE_DAMAGE = 0.0

STABHIT_FOR_BREAKING_ALLIANCE_IN_WAR = 0 -- Alliance System
